name: Development Pipeline

on:
    push:
        branches: [master]
    pull_request:
        branches: [develop]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            # 1. Checkout & Setup
            - name: Checkout & Setup Node.js
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            # 2. Install dependencies
            - name: Install dependencies
              run: npm ci

            # 3. Code Quality Checks (Lint, Prettier, Type-check)
            - name: Run Code Quality Checks
              run: |
                  npm run lint || true
                  npm run format:check || true
                  npx tsc --noEmit || true

            # 4. Run Tests
            - name: Run Unit Tests & Coverage
              run: |
                  npm run test:run
                  npm run test:coverage

            # 5. Build & Deploy
            - name: Build & Deploy
              run: |
                  npm run build
                  npx vercel --prod --yes --token=${{ secrets.TRELLO_FRONTEND_VERCEL_TOKEN }}
              env:
                  VERCEL_ORG_ID: ${{ vars.TRELLO_FRONTEND_VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ vars.TRELLO_FRONTEND_VERCEL_PROJECT_ID }}
                  VITE_TRELLO_LIKE_API_URL: ${{ vars.VITE_TRELLO_LIKE_API_URL }}
